### ISSUE TITLE
string to pt-br not found after login

### ISSUE THREAD

**Issue by EtereosDawn** [DRSchlaubi/tonbrett#6]
I report this error

![image](https://github.com/DRSchlaubi/tonbrett/assets/34200212/313de0f4-88b5-4f96-9a6a-45ab4491bb49)

**Comment by DRSchlaubi** [comment]
What the heck that's odd.

This looks like some distro of Linux, right?
That means authentication works differently, does the login screen before this work?

Also could you check the `~/Tonbrett` folder for logs

**Comment by EtereosDawn** [comment]
Yes, fedora linux 39. I'm using the flatpak version.  I checked the files and found only a config,json with my token inside.

**Comment by DRSchlaubi** [comment]
Could you try running the app from console?

**Comment by EtereosDawn** [comment]
Sorry for the lack of information, here it is.  I also tested with the binaries available in releases and the same thing happens.

```
./Tonbrett
Exception in thread "AWT-EventQueue-0" cafe.adriel.lyricist.LyricistException: Strings for language tag pt-BR not found
	at cafe.adriel.lyricist.Lyricist.getStrings(Lyricist.kt:36)
	at cafe.adriel.lyricist.Lyricist.<init>(Lyricist.kt:15)
	at cafe.adriel.lyricist.LyricistComposeKt.rememberStrings(LyricistCompose.kt:19)
	at cafe.adriel.lyricist.StringsKt.rememberStrings(Strings.kt:30)
	at dev.schlaubi.tonbrett.app.TonbrettAppKt.TonbrettApp(TonbrettApp.kt:45)
	at dev.schlaubi.tonbrett.app.desktop.MainKt$startActualApplication$1$1$2.invoke(Main.kt:90)
	at dev.schlaubi.tonbrett.app.desktop.MainKt$startActualApplication$1$1$2.invoke(Main.kt:89)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at dev.schlaubi.tonbrett.app.api.ApiKt.ProvideContext(Api.kt:78)
	at dev.schlaubi.tonbrett.app.desktop.MainKt$startActualApplication$1$1.invoke(Main.kt:89)
	at dev.schlaubi.tonbrett.app.desktop.MainKt$startActualApplication$1$1.invoke(Main.kt:74)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:129)
	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:128)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:169)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2469)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2738)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3353)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:3304)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:781)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1097)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:569)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
	at androidx.compose.ui.ComposeScene.render(ComposeScene.skiko.kt:543)
	at androidx.compose.ui.awt.ComposeBridge$skikoView$1$onRender$1.invoke(ComposeBridge.desktop.kt:178)
	at androidx.compose.ui.awt.ComposeBridge$skikoView$1$onRender$1.invoke(ComposeBridge.desktop.kt:177)
	at androidx.compose.ui.awt.ComposeBridge.catchExceptions(ComposeBridge.desktop.kt:150)
	at androidx.compose.ui.awt.ComposeBridge.access$catchExceptions(ComposeBridge.desktop.kt:64)
	at androidx.compose.ui.awt.ComposeBridge$skikoView$1.onRender(ComposeBridge.desktop.kt:177)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:548)
	at org.jetbrains.skiko.redrawer.AWTRedrawer.update(AWTRedrawer.kt:54)
	at org.jetbrains.skiko.redrawer.LinuxOpenGLRedrawer$Companion$frameDispatcher$1.invokeSuspend(LinuxOpenGLRedrawer.kt:117)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.awt.ComposeBridge$coroutineExceptionHandler$1@14c7056c, androidx.compose.runtime.BroadcastFrameClock@7b140b60, StandaloneCoroutine{Cancelling}@a0cbf45, FlushCoroutineDispatcher@56052c91]



```

**Comment by DRSchlaubi** [comment]
The flat oak just downloads those, so that's not a surprise, thanks for the stacktrace, obviously it shouldn't just crash for a language without translation, not 100% sure why this happens

**Comment by DRSchlaubi** [comment]
Ok I think I found the issue, instead of setting the current language as the preferred language, it sets it as the default causing the error, I can't fix this rn, but will try to fix it tmr
